[01:54:35 PM]Log opened
[01:54:35 PM]ERROR: Traceback (most recent call last):
[01:54:35 PM]  File "/I/M1/tester.py", line 7, in <module>
[01:54:35 PM]    a = stdin.read("")
[01:54:35 PM]TypeError: an integer is required
[01:56:22 PM]Log opened
[01:56:31 PM]User: a
[01:56:31 PM]ended cleanly (The user won)
