[05:04:33 PM]Log opened, IP:Glycan
[05:04:33 PM]Proc: Once upon a day, you were a-walking in a forest, when you accidentally stepped on some railroads, upon which you were driven, against your will, to a cave and thrown within. Good thing you have that handy light source in your pocket.[05:04:33 PM]Proc: 
[05:04:33 PM]Proc: B7[05:04:33 PM]Proc: 
[05:04:33 PM]Proc: Behind you, you see not only the awesome foe that is the Rough Ground of Unwalkability, but also an Indestructible Fallen Log, which had fallen immediately after your entrance. There is no escape, but forward. Such is life, for those lacking in motivation. Exits: S[05:04:33 PM]Proc: 
[05:04:33 PM]Proc: Where do you want to go?  [05:04:57 PM]Log Closed
[09:52:08 PM]Log opened, IP:Glycan
[09:52:08 PM]Proc: Once upon a day, you were a-walking in a forest, when you accidentally stepped on some railroads, upon which you were driven, against your will, to a cave and thrown within. Good thing you have that handy light source in your pocket.[09:52:08 PM]Proc: 
[09:52:08 PM]Proc: Behind you, you see not only the awesome foe that is the Rough Ground of Unwalkability, but also an Indestructible Fallen Log, which had fallen immediately after your entrance. There is no escape, but forward. Such is life, for those lacking in motivation. Exits: S[09:52:08 PM]Proc: 
[09:52:08 PM]Proc: Where do you want to go?  [09:52:11 PM]User: S
[09:52:12 PM]User: S
[09:52:13 PM]User: S
[09:52:14 PM]User: asdkaoslkd
[09:03:12 PM]Log opened, IP:Glycan
[09:03:12 PM]ERROR: Upon execvpe ~/QFTSOM/main.py [] in environment id 162599636
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 414, in _fork
    executable, args, environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 456, in _execChild
    os.chdir(path)
OSError: [Errno 2] No such file or directory: '~/QFTSOm'
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:03:12 PM]ended with errors!

[09:03:31 PM]Log Closed
[09:04:24 PM]Log opened, IP:Glycan
[09:04:24 PM]ERROR: Upon execvpe ~/QFTSOM/main.py [] in environment id 163065068
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 414, in _fork
    executable, args, environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 456, in _execChild
    os.chdir(path)
OSError: [Errno 2] No such file or directory: '~/QFTSOM'
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:04:24 PM]ended with errors!

[09:05:02 PM]Log Closed
[09:05:28 PM]Log opened, IP:Glycan
[09:05:28 PM]ERROR: Upon execvpe ~/QFTSOM/main.py [] in environment id 156826860
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 414, in _fork
    executable, args, environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 460, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 368, in _execvpe
    func(file, *argrest)
OSError: [Errno 2] No such file or directory
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:05:28 PM]ended with errors!

[09:05:54 PM]Log Closed
[09:06:54 PM]Log opened, IP:Glycan
[09:06:55 PM]Proc: Do kill it!
Python has bite'd  Tail!
Python's Tail took 5 DMG, it now has 25
0: bite
1: whip
Choice? [09:07:18 PM]User: 1
[09:09:19 PM]Log Closed
[09:09:42 PM]Log opened, IP:Glycan
[09:09:42 PM]Proc: Do kill it!
Python has whip'd  Head!
Python's Head took 10 DMG, it now has 10
0: bite
1: whip
Choice? [09:09:55 PM]User: 1
[02:22:29 PM]Log Closed
[09:30:42 PM]Log opened, IP:Glycan
[09:30:42 PM]ERROR: Upon execvpe python -c 'print 'die!';import sys;f = open('TEST');while 1:f.write(sys.stdin.read(1));f.flush()) [] in environment id 172798676
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 414, in _fork
    executable, args, environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 460, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:30:42 PM]ended with errors!

[09:30:54 PM]Log Closed
[09:31:29 PM]Log opened, IP:Glycan
[09:31:29 PM]ERROR: Upon execvpe python -c 'print 'die!';import sys;f = open('TEST');while 1:f.write(sys.stdin.read(1));f.flush())' [] in environment id 148296404
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 414, in _fork
    executable, args, environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 460, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:31:29 PM]ended with errors!

[09:39:14 PM]Log Closed
[09:40:49 PM]Log opened, IP:Glycan
[09:40:49 PM]ERROR: Upon execvpe exec("print \'a\';import sys\nwhile 1: f.write(sys.stdin.read(1)); f.flush()") [] in environment id 172569300
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 414, in _fork
    executable, args, environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 460, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:40:49 PM]ended with errors!

[09:41:45 PM]Log Closed
[09:43:55 PM]Log opened, IP:Glycan
[09:43:55 PM]ERROR: Upon execvpe python -c r\'exec("print \'a\';import sys\nwhile 1: f.write(sys.stdin.read(1)); f.flush()")\' [] in environment id 150127316
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 414, in _fork
    executable, args, environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 460, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:43:55 PM]ended with errors!

[09:45:50 PM]Log Closed
[09:46:14 PM]Log opened, IP:Glycan
[09:46:14 PM]Proc: a
[09:46:14 PM]ERROR: Traceback (most recent call last):
  File "/I/M1/tester.py", line 5, in <module>
    f.write(sys.stdin.read(1))
NameError: name 'f' is not defined
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:46:14 PM]ended with errors!

[09:47:33 PM]Log Closed
[09:50:44 PM]Log opened, IP:Glycan
[09:50:57 PM]User: a
[09:50:58 PM]User: v
[09:52:54 PM]Log Closed
[09:55:43 PM]Log opened, IP:Glycan
[09:55:46 PM]Proc: a
MOO!
[09:55:46 PM]ERROR: Traceback (most recent call last):
[09:55:46 PM]ERROR:   File "/I/M1/tester.py", line 26, in <module>
[09:55:46 PM]ERROR:     [09:55:46 PM]ERROR: f.write(sys.stdin.read(1))
[09:55:46 PM]ERROR: NameError[09:55:46 PM]ERROR: : [09:55:46 PM]ERROR: name 'sys' is not defined[09:55:46 PM]ERROR: 
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:55:46 PM]ended with errors!

[09:57:12 PM]Log Closed
[09:57:41 PM]Log opened, IP:Glycan
[09:57:44 PM]Proc: a
MOO!
[09:57:44 PM]ERROR: Traceback (most recent call last):
[09:57:44 PM]ERROR:   File "/I/M1/tester.py", line 26, in <module>
[09:57:44 PM]ERROR:     [09:57:44 PM]ERROR: c = stdin.read(1)
[09:57:44 PM]ERROR: AttributeError[09:57:44 PM]ERROR: : [09:57:44 PM]ERROR: Wrap instance has no attribute 'read'[09:57:44 PM]ERROR: 
*--- Failure #7 ---
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
*--- End of Failure #7 ---
[09:57:44 PM]ended with errors!

[10:04:00 PM]Log Closed
[10:04:58 PM]Log opened, IP:Glycan
[10:04:59 PM]Proc: Do kill it!
Python has headbut'd  Head!
Python's headbut has 5 speed
MAN's Head took 3 DMG, it now has 17
0: headbut
1: punch
2: stab
3: punch
4: kick
5: kick
Choice? [10:05:05 PM]User: 2
[10:05:06 PM]Log opened, IP:Glycan
[10:05:06 PM]Proc: Do kill it!
Python has whip'd  Arm!
Python's whip has 4 speed
MAN's Arm took 10 DMG, it now has 20
0: headbut
1: punch
2: stab
3: punch
4: kick
5: kick
Choice? [10:05:31 PM]User: asd
[10:05:32 PM]User: asdashj
[10:05:44 PM]User: 2
[10:05:54 PM]Log Closed
[10:06:01 PM]Log Closed
[10:06:33 PM]Log opened, IP:Glycan
[10:06:33 PM]Proc: Do kill it!
Python has whip'd  Leg!
Python's whip has 4 speed
MAN's Leg took 10 DMG, it now has 20
0: headbut
1: punch
2: stab
3: punch
4: kick
5: kick
Choice? [10:06:59 PM]User: 2
[10:07:01 PM]User: 3
[10:09:07 PM]Log Closed
[10:09:30 PM]Log opened, IP:Glycan
[10:09:30 PM]Proc: Do kill it!
Python has whip'd  Arm!
Python's whip has 4 speed
MAN's Arm took 10 DMG, it now has 20
0: headbut
1: punch
2: stab
3: punch
4: kick
5: kick
Choice? [10:09:42 PM]User: 3
[10:11:13 PM]Log Closed
[10:11:51 PM]Log opened, IP:Glycan
[10:11:51 PM]Proc: Do kill it!
Python has headbut'd  Arm!
Python's headbut has 5 speed
Python's headbut missed!
0: headbut
1: punch
2: stab
3: punch
4: kick
5: kick
Choice? [10:11:54 PM]User: 3
